//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace ShackBattles.Data
{
    using System;
    using System.Collections.Generic;
    
    public partial class UserBattle
    {
        public int UserBattlesKey { get; set; }
        public int UsersKey { get; set; }
        public int BattleKey { get; set; }
    
        public virtual Battle Battle { get; set; }
        public virtual User User { get; set; }
    }
}
